version: "3.11"

x-app: &default-app
  build:
    context: "."
  volumes:
    - .:/app
  restart: "unless-stopped"
  environment:
    - SECRET_KEY=${SECRET_KEY}

services:
  web:
    <<: *default-app
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_password@db:5432/postgres_db

  tailwind:
    <<: *default-app
    command: "python manage.py tailwind start"
    tty: true

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
